// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDNa4dEvLxvHC7RdgChQKNCZWXn6GGLC4',
    appId: '1:86691516119:android:6ca42d089be98821f1aa92',
    messagingSenderId: '86691516119',
    projectId: 'skin-care-app-d1ee9',
    databaseURL: 'https://skin-care-app-d1ee9-default-rtdb.firebaseio.com',
    storageBucket: 'skin-care-app-d1ee9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw7rsxLZ8LxLVjB_HxqJ-WAP48_ij9tmA',
    appId: '1:86691516119:ios:7a498ae1163836fff1aa92',
    messagingSenderId: '86691516119',
    projectId: 'skin-care-app-d1ee9',
    databaseURL: 'https://skin-care-app-d1ee9-default-rtdb.firebaseio.com',
    storageBucket: 'skin-care-app-d1ee9.appspot.com',
    androidClientId: '86691516119-huq28jbnl5h2v7pssojarb72pbjil0jv.apps.googleusercontent.com',
    iosClientId: '86691516119-82qvukk3tof3mhb5f7p1i75hjcnv3gk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
